import React from "react";
import { View, Text, SafeAreaView, ScrollView } from "react-native";
import { FontAwesome } from "@expo/vector-icons";

const AboutUs = ({navigation}) => {

    return (
        <SafeAreaView className="flex-1 bg-blackapp h-full w-full">
            <ScrollView>
                <View className="flex h-full w-full px-6">
                    <View className="flex h-auto w-auto justify-center items-center px-6 mt-6">
                        <Text className="text-3xl mb-8 text-whiteapp text-center">Election forecasting and voter behavior analysis</Text>
                        <Text className="text-base text-whiteapp text-justify">Our app is at the forefront of innovation, utilizing sophisticated AI technology to analyze vast amounts of data generated by users' interactions with various political platforms and news outlets.</Text>
                    </View>
                    <View className="flex w-auto h-auto mx-6 py-6 my-6 justify-center items-center bg-whiteapp rounded-lg">
                        <Text className="text-3xl mb-4 text-blackapp">Features</Text>
                        <View className="w-44 h-auto mb-3 bg-blackapp rounded-full items-center"><Text className="text-md p-4 text-whiteapp">Election Graphs</Text></View>
                        <View className="w-44 h-auto mb-3 bg-blackapp rounded-full items-center"><Text className="text-md p-4 text-whiteapp">Demographic Insight</Text></View>
                        <View className="w-44 h-auto mb-3 bg-blackapp rounded-full items-center"><Text className="text-md p-4 text-whiteapp">Predictions</Text></View>
                        <View className="w-44 h-auto bg-blackapp rounded-full items-center"><Text className="text-md p-4 text-whiteapp">Voter Tendencies</Text></View>
                    </View>
                </View>
            </ScrollView>
        </SafeAreaView>
    )
}

export default AboutUs;